library: "qfT0ZuGSRCWBI5sG0rl5hw"
false_lib: "7-Ft-lBdTCSoe56OQkETSQ"

name: "Murray, Steven G."
started: 2013
orcid: "0000-0003-3059-3823"

affiliations:
  #- "School of Earth and Space Exploration, Arizona State University"
  - "ASU"
  - "University of Western Australia"
  - "UWA"
  #- "Curtin University"
  - "Curtin"
  - "-"
  #- "ICRAR, University of Western Australia, 35 Stirling Highway, Crawley, Western Australia 6009, Australia"
  #- "ARC Centre of Excellence for All-Sky Astrophysics (CAASTRO), Australia"
  - "Arizona State University"