library = "qfT0ZuGSRCWBI5sG0rl5hw"
false_lib = "7-Ft-lBdTCSoe56OQkETSQ"

name = "Murray, Steven G."
started = 2013
orcid = "0000-0003-3059-3823"

affiliations = [
    "ASU",
    "University of Western Australia",
    "UWA",
    "Curtin",
    "-",
    "Arizona State University",
    "Scuola Normale Superiore",
]

orcid_not_claimable = [
    "2019BAAS...51c.394L",
    "2017mwa..prop..A12W",
]
